export * from './GenericAdmissionService';
export * from './ApplicantService';
export * from './RegistrationService';
export * from './AdmissionWaveService';
export * from './AdmissionAuditService';
export * from './AdmissionVerificationService';
export * from './AdmissionSelectionService';
export * from './AdmissionResultService';
export * from './AdmissionConversionService';
